name: dressed_up
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.4.0

  # Shared Pref
  shared_preferences: ^2.3.2

  # HTTP Requests
  dio: ^5.1.1

  # Navigation
  go_router: ^14.3.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # MobX State Management Dependencies
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6

  # Dependency Injection
  get_it: ^7.2.0

  # Other Dependencies
  flutter_hooks: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mobx_codegen: ^2.1.1
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google_icon.png
    - assets/images/dressed_up_logo.png

flutter_native_splash:
  android: true
  ios: true
  web: false
  fullscreen: true

  android_12:
    color: "#f1efe7"
    image: assets/images/dressed_up_logo.png
  
